// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1yfAFZ3MEat5ru-eIKWjAyftwuf3u6w',
    appId: '1:197198612147:web:2a572de51c7f646392d2c6',
    messagingSenderId: '197198612147',
    projectId: 'pildtrip360',
    authDomain: 'pildtrip360.firebaseapp.com',
    storageBucket: 'pildtrip360.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVTfAcYiKSqOKSHiTZRDP-YFTCRDVhOv4',
    appId: '1:197198612147:android:16744156dcf12a8092d2c6',
    messagingSenderId: '197198612147',
    projectId: 'pildtrip360',
    storageBucket: 'pildtrip360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuPHvAcwW-njkmK4DweprYnXr8yOqgwU',
    appId: '1:197198612147:ios:c0f757cbee127ca492d2c6',
    messagingSenderId: '197198612147',
    projectId: 'pildtrip360',
    storageBucket: 'pildtrip360.firebasestorage.app',
    iosBundleId: 'com.example.fieldtrip361',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJuPHvAcwW-njkmK4DweprYnXr8yOqgwU',
    appId: '1:197198612147:ios:c0f757cbee127ca492d2c6',
    messagingSenderId: '197198612147',
    projectId: 'pildtrip360',
    storageBucket: 'pildtrip360.firebasestorage.app',
    iosBundleId: 'com.example.fieldtrip361',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1yfAFZ3MEat5ru-eIKWjAyftwuf3u6w',
    appId: '1:197198612147:web:87d0d8761b285d0a92d2c6',
    messagingSenderId: '197198612147',
    projectId: 'pildtrip360',
    authDomain: 'pildtrip360.firebaseapp.com',
    storageBucket: 'pildtrip360.firebasestorage.app',
  );
}
