@startuml DFD_Level0
title **DFD Model — Level 0**

skinparam backgroundColor White
skinparam defaultFontName Arial
skinparam defaultFontSize 11
skinparam linetype ortho
skinparam arrowColor #1F2937
skinparam arrowThickness 1.3
skinparam arrowFontSize 9

skinparam rectangle<<ent>> {
  BackgroundColor White
  BorderColor Black
  RoundCorner 0
  FontStyle bold
  FontSize 12
}
skinparam rectangle<<proc>> {
  BackgroundColor #DBEAFE
  BorderColor #2563EB
  RoundCorner 20
  FontStyle bold
  FontSize 14
}

left to right direction

rectangle "Student" as STU <<ent>>
rectangle "Parent"  as PAR <<ent>>

rectangle "  FieldTrip360\n     System  " as SYS <<proc>>

rectangle "Teacher"      as TCH <<ent>>
rectangle "School Admin" as ADM <<ent>>

STU -right-> SYS : QR Attendance, GPS Data
STU -right-> SYS : SOS Alert
SYS -left->  STU : Trip Notifications (Depart/Arrive)
SYS -left->  STU : Geofence Warning
STU -right-> SYS : Communication via Chat
SYS -left->  STU : Communication via Chat

PAR -right-> SYS : Child Link Request (QR / LRN)
PAR -right-> SYS : Communication via Chat
SYS -left->  PAR : Student Location Updates & SOS Notif
SYS -left->  PAR : Communication via Chat

SYS -right-> TCH : Attendance Confirmation
SYS -right-> TCH : Geofence & SOS Alerts
TCH -left->  SYS : Roll Call
TCH -left->  SYS : Communication via Chat
SYS -right-> TCH : Communication via Chat

ADM -left->  SYS : Trip Info, Destination Details
ADM -left->  SYS : Geofence Configuration
SYS -right-> ADM : Monitoring Reports
SYS -right-> ADM : Communication via Chat
ADM -left->  SYS : Communication via Chat

@enduml
